name: pytorch-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.7
  - git
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - matplotlib
  - numpy
  - optuna
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - python=3.9
  - python-language-server
  - pytorch=2.0
  - pytorch-lightning
  - tensorboard
  - torchaudio
  - torchmetrics
  - torchtext
  - torchvision=0.15.0
  - xeus-python
